use crate::generation2::{apply_repetition_penalty};
use anyhow::{Result, anyhow};
use async_trait::async_trait;
use edgetransformers::CpuKVCache;
use edgetransformers::decoder::TransformerDecoder;
use edgetransformers::models::base::GenerationConfig;
use edgetransformers::models::download_model_files;
use edgetransformers::models::project_to_vocab;
use edgetransformers::models::{DecoderLanguageModel, LanguageModel, ModelArchitecture, ModelType};
use edgetransformers::prelude::*;
use edgetransformers::traits::{Decoder, DecoderArchitecture, DecoderOutput, LanguageModelConfig};
use edgetransformers::models::base::DecodingStrategy;
use edgetransformers::weights::ModelWeights;
use ndarray::{Array2, Array3, s};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokenizers::Tokenizer;
mod configs;
mod gpt2;
mod llama;
mod llama_configs;

pub use configs::Gpt2Config;
pub use gpt2::Gpt2Model;
pub use llama_configs::LlamaConfig;
pub use llama::LlamaModel;
