/// The type of a token being yielded by the generation stream.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenType {
    /// A token from the initial prompt.
    Prompt,
    /// A token newly generated by the model.
    Generated,
}

/// A container for a token and its metadata from the generation stream.
#[derive(Debug, Clone)]
pub struct StreamedToken {
    /// The decoded text representation of the token.
    pub text: String,
    /// The ID of the token in the vocabulary.
    pub id: u32,
    /// Indicates whether this token was part of the prompt or generated.
    pub token_type: TokenType,
}